import type { NextPage } from 'next';
import Head from 'next/head';
import useAxios from 'hooks/useAxios';
import axios from 'axios';

import Deal from 'components/Deal/Deal';
import { DealItemProps } from 'components/Deal/types';

import Carousel from 'components/Carousel/Carousel';
import Main from 'components/Main';

import styled from '@emotion/styled';
import { Fragment } from 'react';
import Mypage from 'components/Mypage';
interface HomeProps {
    conItems: DealItemProps[];
}
const Home: NextPage<HomeProps> = ({ conItems }) => {
    useAxios('/con-items/soon');

    return (
        <Fragment>
            <MainWrapper>
                <Head>
                    <title>NCNC App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Mypage />
                <Carousel />
                <Main />
                <Deal onDealItems={conItems} />
            </MainWrapper>
        </Fragment>
    );
};

const MainWrapper = styled.div`
    background-color: #fff;
`;

export async function getStaticProps() {
    const fetchUrl = `https://api2.ncnc.app/con-items/soon`;
    const { data } = await axios.get<{ conItems: DealItemProps[] }>(fetchUrl);
    const conItems = data.conItems;
    return {
        props: { conItems },
    };
}
export default Home;
